### ISSUE TITLE
Remember last project

### ISSUE THREAD

**Issue by deepredsky** [jobn/braid#11]
Currently you need to select the project everytime you login. This can be quite annoying if you are mostly just going to one project. It would be great if it would autoselect the last project.

**Comment by jobn** [comment]
Im not fully on board with this feature. Currently the project selection is route driven. So you could bookmark the direct link to the project you are working on, or use your browsers suggestion while typing.
implementing https://github.com/jobn/braid/issues/5 would make the on-boarding of new users easier but also influence this issue.

But im open to be convinced otherwise.

**Comment by deepredsky** [comment]
i m good with #5
