### ISSUE TITLE
Drag and drop stories between columns to change state

### ISSUE THREAD

**Issue by jobn** [jobn/braid#41]
rough outline of feature:
- user clicks and holds an anchor (icon) on a story.
- the other columns is rerendered as drop targets
- if the user drops the story on another column the update api request is fired
- state is set optimistically and colums + stories are rerendered
- handle succes/error response

**Comment by kbraak** [comment]
Johannes, as requirements I would suggest adding the following:
* the priority/order would be maintained (when dragging and dropping stories)
* the logged in Braid user is verified as having permission to change the state - otherwise a warning gets shown (e.g. indicating the user must have role 'member' or 'owner')

**Comment by jobn** [comment]
@kbraak all things being equal, changing the `state` attribute on a story would not mess with the ordering. 

The order you see the stories in, is the one that pivotal returns. That order is based on the order the stories have in the current sprint. To this day i haven't found an attribute in the data that represents this order, so im kind of cautions to do any ordering at all.

**Comment by jobn** [comment]
@kbraak review app with the drag n drop feature is deployed here: https://deploy-preview-57--braid.netlify.com/ if you want to test it out
